from .main.home import HomePage as Home
from .tools.posterboard import PosterboardPage as Posterboard
from .tools.status_bar import StatusBarPage as StatusBar
from .tools.springboard import SpringboardPage as Springboard
from .tools.internal import InternalPage as Internal
from .tools.liquidglass import LiquidGlassPage as LiquidGlass
from .tools.daemons import DaemonsPage as Daemons
from .tools.templates import TemplatesPage as Templates
from .tools.passcode import PasscodePage as Passcode
from .main.settings import SettingsPage as Settings